[build]
  publish = "_site"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "9"

[[plugins]]
  package = "@netlify/plugin-sitemap"

[dev]
  command = "npm run dev"
  port = 8080
  targetPort = 8080
  publish = "_site"
  framework = "#custom"
