[build]
  publish = "_site"
  command = "npm run build"

# Konfigurasi untuk Netlify CMS
[[plugins]]
  package = "@netlify/plugin-netlify-cms"

# Redirect dan rewrite rules
[[redirects]]
  from = "/admin/*"
  to = "/admin/:splat"
  status = 200
  force = true

# Redirect untuk akses ke homepage
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
