backend:
  name: git-gateway
  branch: main # Branch yang digunakan untuk konten

# Saat bekerja di lokal, aktifkan ini untuk pengujian lokal
# local_backend: true

# Media folder tempat CMS menyimpan media yang diunggah
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

# Aktivasi publish mode editorial
publish_mode: editorial_workflow

collections:
  # Pengaturan header
  - name: "settings"
    label: "Pengaturan"
    files:
      - name: "header"
        label: "Header"
        file: "_data/settings/header.json"
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Subjudul", name: "subtitle", widget: "string"}
          - label: "Menu Items"
            name: "menuItems"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string", hint: "Nama ikon dari Font Awesome, contoh: home, info-circle"}
      
      - name: "footer"
        label: "Footer"
        file: "_data/settings/footer.json"
        fields:
          - {label: "Deskripsi", name: "description", widget: "text"}
          - {label: "Copyright Text", name: "copyright", widget: "string"}
          - label: "Social Media"
            name: "socialMedia"
            widget: "list"
            fields:
              - {label: "Platform", name: "platform", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Icon", name: "icon", widget: "string", hint: "Nama ikon dari Font Awesome, contoh: fa-instagram"}
          - label: "Quick Links"
            name: "quickLinks"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}
          - label: "Contact Info"
            name: "contactInfo"
            widget: "object"
            fields:
              - {label: "Alamat", name: "address", widget: "text"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}
          - label: "Legal Links"
            name: "legalLinks"
            widget: "list"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "URL", name: "url", widget: "string"}

  # Hero Section
  - name: "hero"
    label: "Hero Section"
    file: "_data/hero.json"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Subjudul", name: "subtitle", widget: "text"}
      - {label: "Teks Tombol", name: "buttonText", widget: "string"}
      - label: "Slide Background"
        name: "slides"
        widget: "list"
        fields:
          - {label: "Gambar", name: "image", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string"}

  # About Section
  - name: "about"
    label: "About Section"
    file: "_data/about.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - label: "Fitur"
        name: "features"
        widget: "list"
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Deskripsi", name: "description", widget: "text"}
          - {label: "Icon", name: "icon", widget: "string", hint: "Nama ikon dari Font Awesome, contoh: graduation-cap"}

  # Program Section
  - name: "programsSettings"
    label: "Program Settings"
    file: "_data/programsSettings.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}

  - name: "programs"
    label: "Programs"
    folder: "_data/programs"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Status", name: "status", widget: "string", default: "Coming Soon"}
      - {label: "Urutan", name: "order", widget: "number", default: 10}

  # Team Section
  - name: "teamSettings"
    label: "Team Settings"
    file: "_data/teamSettings.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}

  - name: "team"
    label: "Team Members"
    folder: "_data/team"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Nama", name: "name", widget: "string"}
      - {label: "Posisi", name: "position", widget: "string"}
      - {label: "Foto", name: "photo", widget: "image"}
      - {label: "Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Urutan", name: "order", widget: "number", default: 10}

  # Articles Section
  - name: "articlesSettings"
    label: "Articles Settings"
    file: "_data/articlesSettings.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "View All Button Text", name: "viewAllButtonText", widget: "string"}
      - {label: "View All Button URL", name: "viewAllButtonUrl", widget: "string"}

  - name: "articles"
    label: "Articles"
    folder: "_data/articles"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Penulis", name: "author", widget: "string"}
      - {label: "Foto Penulis", name: "authorPhoto", widget: "image"}
      - {label: "Tanggal", name: "date", widget: "datetime"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Ringkasan", name: "excerpt", widget: "text"}
      - {label: "Konten", name: "content", widget: "markdown"}
      - {label: "Urutan", name: "order", widget: "number", default: 10}

  # Timeline Section
  - name: "timelineSettings"
    label: "Timeline Settings"
    file: "_data/timelineSettings.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}

  - name: "timeline"
    label: "Timeline Events"
    folder: "_data/timeline"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "Button Text", name: "buttonText", widget: "string", default: "Coming Soon"}
      - {label: "Urutan", name: "order", widget: "number", default: 10}

  # Gallery Section
  - name: "gallerySettings"
    label: "Gallery Settings"
    file: "_data/gallerySettings.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "View All Button Text", name: "viewAllButtonText", widget: "string"}
      - {label: "View All Button URL", name: "viewAllButtonUrl", widget: "string"}

  - name: "gallery"
    label: "Gallery Items"
    folder: "_data/gallery"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Tanggal", name: "date", widget: "string"}
      - {label: "Gambar", name: "image", widget: "image"}
      - {label: "Urutan", name: "order", widget: "number", default: 10}

  # Contact Section
  - name: "contact"
    label: "Contact Section"
    file: "_data/contact.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - label: "Contact Info"
        name: "contactInfo"
        widget: "object"
        fields:
          - {label: "Instagram", name: "instagram", widget: "string"}
          - {label: "Instagram URL", name: "instagramUrl", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Alamat", name: "address", widget: "text"}
      - {label: "Formspree ID", name: "formspreeId", widget: "string", required: false, hint: "ID dari Formspree untuk menangani form pengiriman"}

  # Location Section
  - name: "location"
    label: "Location Section"
    file: "_data/location.json"
    fields:
      - {label: "Label Section", name: "sectionLabel", widget: "string"}
      - {label: "Judul", name: "title", widget: "string"}
      - {label: "Deskripsi", name: "description", widget: "text"}
      - {label: "Map URL", name: "mapUrl", widget: "string"}
      - {label: "Nama Lokasi", name: "locationName", widget: "string"}
      - {label: "Alamat Lengkap", name: "fullAddress", widget: "text"}
      - {label: "Directions URL", name: "directionsUrl", widget: "string"}
      - label: "CTA"
        name: "cta"
        widget: "object"
        fields:
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Deskripsi", name: "description", widget: "text"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
          - {label: "Button URL", name: "buttonUrl", widget: "string"}
